version: "3.6"

services:
  web:
    image: nginx
    volumes:
      - ./public:/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: "no"
    links:
      - php
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    restart: "no"
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    restart: "no"

